homeassistant:
  name: Home
  latitude: !secret my_gps_lat
  longitude: !secret my_gps_lon
  elevation: 19
  unit_system: metric
  time_zone: !secret my_loc
  customize: !include customize.yaml
################################################# HTTP SSL & DUCKDNS #############################################
http: !include http.yaml
################################################ M Q T T BROKER INFO BELOW #######################################
mqtt: !include mqtt.yaml
################################################# xiaomi gateway #################################################
xiaomi_aqara: !include xiaomi.yaml
#################################################### COMPONENTS ##################################################
device_tracker: !include device_tracker.yaml
history_graph: !include history_graph.yaml
input_boolean: !include input_boolean.yaml
media_player: !include media_player.yaml
panel_iframe: !include panel_iframe.yaml
automation: !include automations.yaml
recorder: !include recorder.yaml
history: !include history.yaml
weather: !include weather.yaml
climate: !include climate.yaml
homekit: !include homekit.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
switch: !include switch.yaml
light: !include lights.yaml
group: !include groups.yaml
media_extractor:
conversation:
discovery:
frontend:
logbook:
config:
ffmpeg:
cloud:
map:
ios:
sun:
tts:
#